version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_stocks
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
      FLASK_APP: "app.py"
      ALPHAVANTAGE_API_KEY: "ISKC9Q4DFAEBJCTB"
